---
- name: Set VyOS hostname
  vars:
    hostname: "{{ hostvars[inventory_hostname][demo_name]['hostname'] }}"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
  vyos.vyos.vyos_config:
    lines:
      - set system host-name "{{ hostname }}"
