---
- hosts: ALL
  gather_facts: no
  vars:
    demo_name: VPN
  tasks:
    - name: Test Connection
      ping:
      register: msg

    - name: set hostname
      include_role:
        name: hostname

- hosts: ISP1, ISP2
  gather_facts: no
  vars:
    demo_name: VPN
  tasks:
    - name: set ip address
      include_role:
        name: ip-address

    - name: set bgp with ISP
      include_role:
        name: bgp

- hosts: HOME, HQ, BRANCH
  gather_facts: no
  vars:
    demo_name: VPN
  tasks:
    - name: set ip address
      include_role:
        name: ip-address

    - name: set bridge
      include_role:
        name: bridge

    - name: set DHCP server
      include_role:
        name: dhcp

#    - name: set NAT
#      include_role:
#        name: nat
#    - name: set wireguard to HQ
#    - name: set BGP
