---
- name: Set DHCP
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    dhcp: "{{ hostvars[inventory_hostname][demo_name]['dhcp'] }}"
  vyos.vyos.vyos_config:
    src: dhcp.j2
