---
- name: Set NAT
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    nat: "{{ hostvars[inventory_hostname][demo_name]['nat'] }}"
  vyos.vyos.vyos_config:
    src: nat.j2
    save: true
