---
- name: Set Bridge
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    bridge: "{{ hostvars[inventory_hostname][demo_name]['bridge'] }}"
  vyos.vyos.vyos_config:
    src: bridge.j2
    save: true
