---
- name: Set Wireguard
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    wireguard: "{{ hostvars[inventory_hostname][demo_name]['wireguard'] }}"
  vyos.vyos.vyos_config:
    src: wireguard.j2
    save: true
